import type { GuidedTourStep } from "@/components/guided-tour/guided-tour-engine";

export const RH_TOUR_STORAGE_KEY = "leaft_rh_guided_tour_v2_done";

export function buildRhTourSteps(): GuidedTourStep[] {
  return [
    {
      id: "intro",
      kind: "modal",
      title: "Bienvenue sur Leaft",
      body: "Ce guide vous présente les sections principales de votre espace RH. Cliquez sur chaque entrée du menu lorsque nous vous l’indiquons.",
    },
    {
      id: "dashboard",
      kind: "highlight",
      pathname: "/dashboard",
      selector: '[data-tour="rh-dashboard"]',
      title: "Tableau de bord",
      body: "Vue d’ensemble : effectifs, masse salariale, entretiens à venir et répartition par département.",
    },
    {
      id: "go_talents",
      kind: "navigate",
      pathname: "/dashboard",
      navSelector: '[data-tour="rh-nav-talents"]',
      waitPathname: "/dashboard/talents",
      title: "Talents",
      body: "Cliquez sur « Talents » pour gérer les fiches collaborateurs.",
      showNext: false,
      scrollToTop: true,
      popoverPlacement: "nav-right",
    },
    {
      id: "talents",
      kind: "highlight",
      pathname: "/dashboard/talents",
      selector: '[data-tour="rh-talents-main"]',
      title: "Gestion des talents",
      body: "Ajoutez, modifiez et consultez les collaborateurs de votre organisation.",
    },
    {
      id: "go_grilles",
      kind: "navigate",
      pathname: "/dashboard/talents",
      navSelector: '[data-tour="rh-nav-grilles"]',
      waitPathname: "/dashboard/grilles",
      title: "Grilles salariales",
      body: "Cliquez sur « Grilles de salaire » pour structurer familles, niveaux et fourchettes.",
      showNext: false,
      scrollToTop: true,
      popoverPlacement: "nav-right",
    },
    {
      id: "grilles",
      kind: "highlight",
      pathname: "/dashboard/grilles",
      selector: '[data-tour="rh-grilles-header"]',
      title: "Grilles",
      body: "Départements, paliers, management et ancienneté : base de votre politique de rémunération.",
      scrollToTop: true,
      popoverPlacement: "page-header",
    },
    {
      id: "go_entretiens",
      kind: "navigate",
      pathname: "/dashboard/grilles",
      navSelector: '[data-tour="rh-nav-entretiens"]',
      waitPathname: "/dashboard/entretiens",
      title: "Entretiens",
      body: "Cliquez sur « Entretiens » pour suivre les entretiens et demandes de RDV.",
      showNext: false,
      scrollToTop: true,
      popoverPlacement: "nav-right",
    },
    {
      id: "entretiens",
      kind: "highlight",
      pathname: "/dashboard/entretiens",
      selector: '[data-tour="rh-entretiens-main"]',
      title: "Entretiens & RDV",
      body: "Planifiez, validez et historisez les entretiens avec vos collaborateurs.",
    },
    {
      id: "go_organigramme",
      kind: "navigate",
      pathname: "/dashboard/entretiens",
      navSelector: '[data-tour="rh-nav-organigramme"]',
      waitPathname: "/dashboard/organigramme",
      title: "Organigramme",
      body: "Cliquez sur « Organigramme » pour la vue hiérarchique.",
      showNext: false,
      scrollToTop: true,
      popoverPlacement: "nav-right",
    },
    {
      id: "organigramme",
      kind: "highlight",
      pathname: "/dashboard/organigramme",
      selector: '[data-tour="rh-organigramme-header"]',
      title: "Organigramme RH",
      body: "Même vue que côté talent, avec les rémunérations selon votre paramétrage de transparence.",
      scrollToTop: true,
      popoverPlacement: "page-header",
    },
    {
      id: "go_parametres",
      kind: "navigate",
      pathname: "/dashboard/organigramme",
      navSelector: '[data-tour="rh-nav-parametres"]',
      waitPathname: "/dashboard/parametres",
      title: "Paramétrage",
      body: "Cliquez sur « Paramétrage » pour la transparence salariale et la facturation.",
      showNext: false,
      scrollToTop: true,
      popoverPlacement: "nav-right",
    },
    {
      id: "parametres",
      kind: "highlight",
      pathname: "/dashboard/parametres",
      selector: '[data-tour="rh-parametres-transparency"]',
      title: "Transparence salariale",
      body: "Activez la transparence et choisissez entre moyenne par département ou salaires exacts (conformité loi).",
    },
    {
      id: "outro",
      kind: "modal",
      title: "Vous êtes prêt",
      body: "Relancez ce guide à tout moment avec ?tour=replay sur le tableau de bord.",
    },
  ];
}
